// Copyright is owned by Veduy.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Jump);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Invincible);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Weapon_FireStaff);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_Damage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_CritChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_CritDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_ProjectileCount);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_ProjectileSpeed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_ProjectileBounces);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_Size);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_Knockback);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Weapon_Duration);

// GameplayCue
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Lightning_Hit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_FireBall_Hit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EC_Damaged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_EC_Death);


// SetByCaller
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_AreaDamageMultiplier);
